import re
from datetime import datetime
from pathlib import Path

from config.settings import ARTIFACTS_DIR


def generate_docx_report(title: str, content: str, sources: list[str] | None = None) -> dict[str, str | int]:
    try:
        from docx import Document
    except ImportError as error:
        raise RuntimeError("Install python-docx to generate DOCX reports.") from error

    ARTIFACTS_DIR.mkdir(parents=True, exist_ok=True)
    output_path = ARTIFACTS_DIR / f"ecommerce_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.docx"

    document = Document()
    document.add_heading(title or "E-commerce Customer Service Report", level=0)
    document.add_paragraph(f"Created: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    document.add_paragraph("Generated by AI Agent Network for E-commerce Customer Service.")

    document.add_heading("Summary", level=1)
    for paragraph in _split_paragraphs(content):
        document.add_paragraph(paragraph)

    if sources:
        document.add_heading("Store Materials Used", level=1)
        for source in sources:
            document.add_paragraph(source, style="List Bullet")

    document.save(output_path)
    return _artifact_result(output_path, "docx")


def _split_paragraphs(content: str) -> list[str]:
    text = _clean_markdown(content)
    paragraphs = [part.strip() for part in re.split(r"\n{2,}", text) if part.strip()]
    return paragraphs or [text or "No content available."]


def _clean_markdown(text: str) -> str:
    text = text or ""
    text = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", text)
    text = re.sub(r"(\*\*|__)(.*?)\1", r"\2", text)
    text = re.sub(r"`([^`]+)`", r"\1", text)
    return text.strip()


def _artifact_result(path: Path, artifact_type: str) -> dict[str, str | int]:
    return {
        "file_name": path.name,
        "file_path": str(path),
        "artifact_type": artifact_type,
        "file_size": path.stat().st_size,
    }
